version: '3'
services:
  another-server:
    container_name: another-server
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sh -c "gunicorn -w 1 -b 0.0.0.0:8080 -k aiohttp.worker.GunicornWebWorker asgi:app"
    ports:
      - 8080:8080

  another-client:
    container_name: another-client
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    command: sh -c "npm run server"
    ports:
      - 3000:3000
    depends_on:
      - another-server